# Generated by Django 5.1.1 on 2024-11-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_book_email_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
    ]
