# Generated by Django 5.1.1 on 2024-11-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_book_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
    ]
